name: Build Windows aria2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:

    # 1. 检出源码
    - name: Checkout
      uses: actions/checkout@v4

    # 2. 安装 MSYS2 + mingw64 环境
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-c-ares
          mingw-w64-x86_64-libssh2
          autoconf
          automake
          gettext
          libtool
          pkgconf

    # 3. 查看源码目录（调试用，可删）
    - name: Show files
      shell: msys2 {0}
      run: |
        pwd
        ls -la
        ls src | head

    # 4. 修改最大连接数
    - name: Patch max connections
      shell: msys2 {0}
      run: |
        sed -i 's/"1-16"/"1-256"/g' src/OptionHandlerImpl.cc

    # 6. 配置编译
    - name: Configure
      shell: msys2 {0}
      run: |
        ./configure \
          --host=x86_64-w64-mingw32 \
          --disable-shared \
          --enable-static \
          --with-openssl \
          --without-gnutls
      env:
        PKG_CONFIG_PATH: /mingw64/lib/pkgconfig
    # 7. 编译
    - name: Build
      shell: msys2 {0}
      run: |
        make -j4

    # 8. 查看输出
    - name: Show output
      shell: msys2 {0}
      run: |
        ls -la src/
        file src/aria2c.exe

    # 9. 上传 exe
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: aria2c-windows
        path: src/aria2c.exe
