name: Build Windows aria2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    # 1️⃣ 检出源码
    - uses: actions/checkout@v3
    - name: Show repo files
      run: cmd /c "dir /s .."
